# Generated by Django 4.2.6 on 2024-01-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('longtext', 'longtext'), ('image', 'image'), ('boolean', 'boolean')], max_length=100),
        ),
    ]
