# Generated by Django 4.2.6 on 2024-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_answer_answer_value_answer_answer_boolean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_longtext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
