# Generated by Django 4.2.6 on 2024-01-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_answer_answer_longtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, default='no_image.jpg', upload_to='upload/'),
        ),
    ]
