# Generated by Django 5.0 on 2024-01-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_answer_answer_boolean_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='description_de',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_value',
            new_name='value_de',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_longtext',
        ),
        migrations.AddField(
            model_name='question',
            name='description_en',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='value_en',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
