# Generated by Django 5.0 on 2024-01-11 18:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_description_question_description_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='entry',
            name='language',
            field=models.CharField(default='#Daeded', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('longtext', 'longtext'), ('image', 'image'), ('color', 'color'), ('boolean', 'boolean')], max_length=100),
        ),
    ]
