# Generated by Django 5.0 on 2024-01-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_answer_answer_color_entry_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'answer_text'), ('longtext', 'answer_longtext'), ('image', 'answer_image'), ('color', 'answer_color'), ('boolean', 'answer_boolean')], max_length=100),
        ),
    ]
