# Generated by Django 5.0 on 2024-01-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_question_special_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('answer_text', 'text'), ('answer_longtext', 'longtext'), ('answer_image', 'image'), ('answer_color', 'color'), ('answer_boolean', 'boolean')], max_length=100),
        ),
    ]
