# Generated by Django 5.0 on 2024-01-14 21:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
