# Generated by Django 4.2.6 on 2024-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_entry_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, default='no_image.webp', upload_to='upload'),
        ),
    ]
