# Generated by Django 5.0 on 2024-01-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_answer_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
