# Generated by Django 5.0 on 2024-01-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_entry_visible'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('interview', 'sort_id'), name='unique_sort_id'),
        ),
    ]
