# Generated by Django 5.0 on 2024-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_question_unique_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sort_id',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
