# Generated by Django 4.2.6 on 2024-01-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_question_sort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='preview_image',
            field=models.ImageField(blank=True, default='no_image.webp', upload_to='upload'),
        ),
    ]
