# Generated by Django 4.2.6 on 2024-01-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_entry_preview_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_sort_id',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='None', max_length=254),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('interview', 'sort_id', 'name'), name='unique_fields'),
        ),
    ]
