# Generated by Django 4.2.6 on 2024-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_question_unique_sort_id_author_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_fields',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('email', 'name'), name='unique_athor'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('interview', 'sort_id', 'name'), name='unique_question'),
        ),
    ]
