# Generated by Django 4.2.6 on 2024-01-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_question_unique_fields_author_unique_athor_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='unique_athor',
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
