# Generated by Django 5.0.1 on 2024-01-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_author_unique_athor_alter_author_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value_en', models.TextField()),
                ('value_de', models.TextField()),
            ],
        ),
    ]
