# Generated by Django 5.0 on 2024-01-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_systemmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='value_de',
            field=models.TextField(blank=True),
        ),
    ]
