# Generated by Django 5.0 on 2024-02-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_systemmessage_value_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_in_friendbook',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemmessage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
