# Generated by Django 5.0 on 2024-02-10 14:25

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_question_show_in_friendbook_alter_systemmessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_color',
            field=colorfield.fields.ColorField(default=None, image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('answer_text', 'text'), ('answer_image', 'image'), ('answer_color', 'color'), ('answer_boolean', 'boolean')], max_length=100),
        ),
    ]
