# Generated by Django 5.0 on 2024-02-10 14:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_answer_answer_color_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
