# Generated by Django 5.0.1 on 2024-01-23 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_write', '0001_initial'),
        ('main', '0018_remove_author_unique_athor_alter_author_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmlink',
            name='author',
        ),
        migrations.AddField(
            model_name='confirmlink',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.entry'),
            preserve_default=False,
        ),
    ]
